print ('')
print ('=========== HELLO WELCOME TO SPACE DUNGEON ==============')
print ('')
print ('To start type in the name of the character')
print ('')
Name = input()
print ('')
print ('Ok now type in the class you want to be')
print ('')
Class = input()
print ('')
print ('Ok now type in how many magic points you want but between 0-100')
print ('')
Majpoints = input()
print ('')
print ('Ok now type in how many Health points you want but between 0-100')
print ('')
Healthpoints = input()
print ('')
print ('So these are your stats')
print ('')
print ('Your Name is:' + Name)
print ('Your Class is:' + Class)
print ('Your Magic points are:' + Majpoints)
print ('Your Health points are:' + Healthpoints)
print ('')
print ('ERROR Space_Dungeon.py HAS STOP WORKING ENDING PRO...........................')
