print('')
print('Hello')
print('')
print('Give me gallons I will Give you liters, okay')
print('')
gallons = int(input())
liters=(gallons * 3.78541)
print("Liters: ", liters)
print('')
print('GOOOOOOOOD BYYYYYYYYE')
print('')
